### ISSUE TITLE
Solution for Windows 7 Installation

### ISSUE THREAD

**Issue by DrOetcker** [zeffy/kb4012218-19#15]
Hey,
First of all! Very nice patch ;)
I bought a new Laptop wich an I7 7700HQ kabylake without OS
The windows 7(Sp1) and 8.1 Installation fails completly. 
UEFI problems, Secureboot etc. are all Not my Problem.
Win10 works fine.
Do you think, that the cpucheck is also applied while the Installationprocess of windows7, so that this Patch could be modified to work with the Installationprocess?

Greetings Oetcker

**Comment by 1n5aN1aC** [comment]
Not possible.

Windows 7 can install completely from disk without internet access, and even SP1 was released FAR before the CPU check was added.

Are you installing from USB?  Most Windows 7 installation are due to Windows 7 not supporting USB3 out of the box, so install fails.. You either need to use a DVD, or 'Slipstream' the USB3 drivers onto the iso used for your flash drive.

**Comment by zeffy** [comment]
No, the cpu check is definitely not in the install process. Have you only tried installing 7 and 8.1? Could be some other general issue and not those versions specifically.

**Comment by DrOetcker** [comment]
Thank u all you for the answers :)
Ok, I just thought, that there is another way to solve it ;)

I tried it from DVD and USB (2.0 device at the 2.0 slot)
Nevertheless, I don't search for answers for my problem here, don't worry ;)

Thank u for the links (I already know them, but thanks :))
And sorry for not adding the Tags^^ Did not found them on the mobile version -.-

**Comment by zeffy** [comment]
No worries, I think github only lets me add tags anyway. :stuck_out_tongue_winking_eye: 

Best of luck with solving your problem!

**Comment by DrOetcker** [comment]
Ok^^ could be a reason, that I did not found them :D
thx!
