### ISSUE TITLE
Unsupported Hardware Message still after the patch

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/kb4012218-19#22]
I used this patch on a Lenovo b570 because it is not a next-gen CPU that got caught in the mixup. It removed the message temporarily—until Windows Update tried to run itself again, it nullified the patch and is giving the unsupported hardware message again. Repeat Repeat Repeat every time Windows update runs on its own after I try to reapply the patch.

**Comment by zeffy** [comment]
From what you're saying it sounds like the patch succeeds when you run it? Is this just since the updates yesterday? 

Can you download [this](https://gist.github.com/zeffy/6d61d93fce8f995583fcdd47f1ee5067/archive/bb3cfc6a1db5be982b2259f071a787b8d155e54b.zip) and run it? It's the same code of as the main patch but it will skip the patching process and gather some debugging information that you can copy/paste into this issue. Normally it would do this automatically if the patching process failed, but it sounds like that isn't the case here. It would help a lot with figuring out the problem.

**Comment by zeffy** [comment]
Just to follow up on this, I looked through the rest of the WUAU files in this last windows update and none of them had any changes from last month's roll up, so I don't believe there is any kind of additional check causing this.

It would be normal to have to reapply the patch after installing new updates, because they will revert the changes the patch makes. But from what I'm understanding in your issue, it sounds like the patch is getting reverted whenever you simply *check* for updates? More information would be very helpful.

**Comment by zeffy** [comment]
Moving main discussion over to #20
