### ISSUE TITLE
no supported updates - unsupported hardware

### ISSUE THREAD

**Issue by marcaccioc** [zeffy/kb4012218-19#34]
Copyright (C) 2017 zeffy <https://github.com/zeffy>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING.txt for details.

Checking system requirements...

Detected supported operating system: Windows 7 x64

Detected that no supported updates are installed! If you are getting
unsupported hardware errors in Windows Update, please create an issue
and I will try to help you out.

https://github.com/zeffy/kb4012218-19/issues

Gathering debugging information, please wait...

Done! Please copy the text from Notepad into your GitHub issue.
Opening log file in 5 seconds...

Press any key to exit...

[aio-wuaueng.dll-patch.bat-debuginfo_2017-05-23_22-52-21_112000.txt](https://github.com/zeffy/kb4012218-19/files/1024351/aio-wuaueng.dll-patch.bat-debuginfo_2017-05-23_22-52-21_112000.txt)

**Comment by zeffy** [comment]
KB4019265 should be supported by the patch script, can you confirm you were using the latest v0.5-rc2 version?

**Comment by marcaccioc** [comment]
I will check when I get home, but I believe I was using the latest version available when I ran it and posted on the 23rd.    I'm surprised that the CPU on this netbook is even a qualifier for microsoft as it is several years old.  Thanks for your help.

**Comment by zeffy** [comment]
Thanks, I appreciate it. I only ask because I've had a few other people who have had this same issue and it turned out they were using an older version. If you still have issues with the latest version please let me know.

Also yeah, I don't know why it's being blocked either. I've had another person here with an old Intel Atom processor who was blocked, too. It's likely a mistake, but given that they have had several months to fix the issue, it seems like Microsoft doesn't really care enough to bother.

**Comment by marcaccioc** [comment]
Looks like it was an older version, sorry about that.   I used the current version and it said it installed successfully.  tks for your help.

**Comment by zeffy** [comment]
Sweet, I'm glad to hear it! Always happy to help.
