### ISSUE TITLE
April, 2017 Preview of Monthly Quality Rollup (KB4015552/KB4015553)

### ISSUE THREAD

**Issue by zeffy** [zeffy/kb4012218-19#5]
Looks like Microsoft has another set of optional updates that replaces KB4012218 and KB4012219 (and thus updates wuaueng.dll), so for now it is probably best to not install these.

Since they are optional, I'm not going to rush out a new patch immediately, but I'll get them out at some point. These preview updates will likely be merged into next month's quality rollup, as has happened in the past.

**Comment by eric4272** [comment]
Thank you for all your hard work zeffy.  Microsoft blocking future updates if you have a Kaby Lake or Ryzen cpu is so wrong and both the cpu's work just fine on windows 7 and 8.1.

**Comment by zeffy** [comment]
You're very welcome, I'm glad to see that so many people are getting use out of these patches! Also I agree, it is an absolutely shameless attempt to cripple Windows 7/8.1 on newer PCs and force people over to Windows 10.

**Comment by MEM-TEK** [comment]
Hi zeffy,

Nice work! I haven't tried your patches since I don't have any computers with the newer "unsupported" CPUs. Yet I think that a lot of people over on the AskWoody.com web site will be willing to try your patches and report back about any issues. Perhaps Woody himself will write about you and your work in an InfoWorld press release!

Best regards,

MEM-TEK

**Comment by zeffy** [comment]
Released new update that closes this issue: https://github.com/zeffy/kb4012218-19/releases

**Comment by zeffy** [comment]
@MEM-TEK Thanks! I see there is a news post on AskWoody.com regarding the patch with quite a lot of comments, which is awesome! Anyone coming from there (or any site, really), is more than welcome to post any feedback or questions they have here.
